### ISSUE TITLE
这个和OI wiki有什么区别吗?

### ISSUE THREAD

**Issue by 00ffcc** [OIerTemplate/OIerTemplateLib#1]

**Comment by 00ffcc** [comment]
好吧这里的代码是真的工业化....

**Comment by UndefBhvr** [comment]
@00ffcc 啊这里的代码是为了方便OIer拖了板子能直接用
不过等到逐渐完善的时候会考虑写注释，那个时候可读性会好一点

总之目标就是写成一个方便使用而便于学习的库
